apply plugin: 'com.android.application'
apply plugin: 'org.jetbrains.kotlin.android'
apply plugin: 'org.jetbrains.kotlin.plugin.compose'

android {
    namespace 'org.scrib.transcriber'
    compileSdk 35
    buildToolsVersion '35.0.0'
    ndkVersion '27.2.12479018'

    defaultConfig {
        applicationId 'org.scrib.transcriber'
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName '0.1'

        ndk {
            abiFilters 'arm64-v8a'
        }
        externalNativeBuild {
            cmake {
                cppFlags '-O3'
                cFlags '-O3'
                arguments '-DANDROID_SUPPORT_FLEXIBLE_PAGE_SIZES=ON'
            }
        }
    }

    buildFeatures {
        aidl true
        compose true
    }

    externalNativeBuild {
        cmake {
            path 'src/main/jni/whisper/CMakeLists.txt'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    kotlinOptions {
        jvmTarget = '17'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    sourceSets {
        main {
            kotlin.srcDirs += 'src/main/kotlin'
        }
    }
}

dependencies {
    implementation platform('androidx.compose:compose-bom:2024.12.01')
    implementation 'androidx.activity:activity-compose:1.9.3'
    implementation 'androidx.compose.material3:material3'
    implementation 'androidx.compose.ui:ui-tooling-preview'
    debugImplementation 'androidx.compose.ui:ui-tooling'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-compose:2.8.7'
    implementation 'androidx.lifecycle:lifecycle-viewmodel-ktx:2.8.7'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.8.1'
}
